[versions]
detekt-version = "1.23.1"
exposed-version = "0.55.0"
flyway-version = "11.1.0"
hikari-version = "6.0.0"
javax-mail-version = "1.6.2"
kafka-apache-version = "3.7.1"
koin-version = "4.0.0"
kotlin-version = "2.1.0"
ktlint-version = "11.6.0"
ktor-version = "3.0.0"
lettuce-version = "6.5.1.RELEASE"
logback-version = "1.5.9"
postgres-version = "42.7.4"
swagger-version = "4.1.0"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed-version" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed-version" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed-version" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed-version" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway-version" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari-version" }
javax-mail = { module = "com.sun.mail:javax.mail", version.ref = "javax-mail-version" }
javax-mail-api = { module = "javax.mail:javax.mail-api", version.ref = "javax-mail-version" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka-apache-version" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-version" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin-version" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin-version" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor-version" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-version" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor-version" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml-jvm", version.ref = "ktor-version" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor-version" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor-version" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common-jvm", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor-version" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor-version" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor-version" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson-jvm", version.ref = "ktor-version" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor-version" }
ktor-swagger-ui = { module = "io.github.smiley4:ktor-swagger-ui", version.ref = "swagger-version" }
lettuce-core = { module = "io.lettuce:lettuce-core", version.ref = "lettuce-version" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres-version" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt-version" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }